### ISSUE TITLE
3.2.1 breaks mkdocs

### ISSUE THREAD

**Issue by gergnz** [facelessuser/pymdown-extensions#84]
```
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: /app/site
ERROR   -  Error building page index.md
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/mkdocs/__main__.py", line 156, in build_command
    ), dirty=not clean)
  File "/usr/local/lib/python2.7/site-packages/mkdocs/commands/build.py", line 380, in build
    build_pages(config, dirty=dirty)
  File "/usr/local/lib/python2.7/site-packages/mkdocs/commands/build.py", line 333, in build_pages
    dump_json)
  File "/usr/local/lib/python2.7/site-packages/mkdocs/commands/build.py", line 189, in _build_page
    site_navigation=site_navigation
  File "/usr/local/lib/python2.7/site-packages/mkdocs/commands/build.py", line 59, in convert_markdown
    extension_configs=config['mdx_configs']
  File "/usr/local/lib/python2.7/site-packages/mkdocs/utils/__init__.py", line 364, in convert_markdown
    extension_configs=extension_configs or {}
  File "/usr/local/lib/python2.7/site-packages/markdown/__init__.py", line 159, in __init__
    configs=kwargs.get('extension_configs', {}))
  File "/usr/local/lib/python2.7/site-packages/markdown/__init__.py", line 187, in registerExtensions
    ext.extendMarkdown(self, globals())
  File "/usr/local/lib/python2.7/site-packages/pymdownx/emoji.py", line 377, in extendMarkdown
    if util.get_arg_count(config['emoji_generator']) == LEGACY_ARG_COUNT:  # pragma: no coverage
  File "/usr/local/lib/python2.7/site-packages/pymdownx/util.py", line 103, in get_arg_count
    count = fn.func_code.co_argcount
AttributeError: 'unicode' object has no attribute 'func_code'
```

After upgrading pymdown-extensions from 3.1 to 3.2.1, we get the above stacktrace.

We are installing the latest versions of other tools. Our requirements file looks like:
```
mkdocs
pygments
pymdown-extensions
mkdocs-material
```

I've reverted to 3.1, which resolves the issue. Let me know if there is anything else I can provide.

**Comment by facelessuser** [comment]
Python version?

**Comment by facelessuser** [comment]
I see it is 2.7.  Can I see your `mkdocs.yml` file?

**Comment by gergnz** [comment]
Hi @facelessuser,

This failed in 2.7 and 3.6 (slightly different error str vs unicode).

mkdocs.yml:
```
extra_javascript:
- https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML
markdown_extensions:
- admonition
- codehilite
- footnotes
- meta
- toc(permalink=true)
- pymdownx.arithmatex
- pymdownx.betterem(smart_enable=all)
- pymdownx.caret
- pymdownx.critic
- pymdownx.emoji:
    emoji_generator: '!!python/name:pymdownx.emoji.to_svg'
- pymdownx.inlinehilite
- pymdownx.magiclink
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences
- pymdownx.tasklist(custom_checkbox=true)
- pymdownx.tilde
pages:
... #redacted
site_name: Foo and bar
theme: material
```

**Comment by facelessuser** [comment]
Try removing the quotes on your emoji_generator.

**Comment by facelessuser** [comment]
Based on what I see in the error and the yaml file.  It looks like you are passing a string as an emoji generator.  By removing the strings, yaml will actually pass the function instead of a string. It is an easy to make mistake. Notice in the examples that there are no quotes: http://facelessuser.github.io/pymdown-extensions/extensions/emoji/#using-with-mkdocs.

Maybe in the future I'll catch strings and issue a an assert. I imagine you aren't the only one that has done this 🙂 .

**Comment by gergnz** [comment]
Thanks @facelessuser, we've found what's causing this. Closing. Apologies for the noise.
